# Generated by Django 2.2.1 on 2019-05-06 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 34, 50, 228111, tzinfo=utc), verbose_name='Published Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('passive', 'Passive')], default='pending', max_length=24, verbose_name='State'),
        ),
    ]
